version: '3.6'

services:
  frontend:
    image: dockersamples/visualizer
    labels:
      - traefik.enable=false
    ports:
      - "9999:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager         
