version: '3.6'
services:

  app-forty:
    image: ymabispo/app-forty:v1
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.backend=app-forty"
        - "traefik.frontend.rule=PathPrefixStrip:/forty"
        - "traefik.port=80"
        - "traefik.enable=true"    
      placement:
        constraints:
          - node.role == worker

  app-phantom:
    image: ymabispo/app-phantom:v1
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.backend=app-phantom"
        - "traefik.frontend.rule=PathPrefixStrip:/phantom"
        - "traefik.port=80"   
        - "traefik.enable=true"    
      placement:
        constraints:
          - node.role == worker

  app-stellar:
    image: ymabispo/app-stellar:v1
    networks:
      - traefik-net 
    deploy:
      labels:
        - "traefik.backend=app-stellar"
        - "traefik.frontend.rule=PathPrefixStrip:/stellar"
        - "traefik.port=80"
        - "traefik.enable=true"    
      placement:
        constraints:
          - node.role == worker
          
networks:
  traefik-net:
    driver: overlay
    external: true