---
- hosts: all
  user: centos
  become: yes
  tasks:
  - name: "Instalando pre-requisitos"
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
  - name: "Configurando repositorio docker"
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644
  - name: "Instalando ultima versao do docker"
    yum:
      name: docker-ce
      state: present
  - name: "Iniciando e habilitando Docker service"
    service:
      name: docker
      state: started
      enabled: yes