---
  - name: Iniciar Manager Swarm
    hosts: managers
    gather_facts: False
    remote_user: centos
    tasks:
      - name: Iniciar Swarm
        command: docker swarm init --advertise-addr {{ inventory_hostname }}

      - name: Pegar Token do Worker
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Exibir Token do Worker
        debug: var=worker_token.stdout

      - name: Token do Manager
        command: docker swarm join-token manager -q
        register: master_token

      - name: Exibir Token do Manager 
        debug: var=master_token.stdout

  - name: Entrar no Swarm
    hosts: workers
    remote_user: centos
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['managers'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Entrar no Swarm Cluster como Worker
        command: docker swarm join --token {{ token }} {{ master }}:2377
        register: worker

      - name: Mostrar Resultado
        debug: var=worker.stdout

      - name: Exibir Erros
        debug: var=worker.stderr